### ISSUE TITLE
Support for free GeoLite2 database?

### ISSUE THREAD

**Issue by JayBrown** [maxmind/geoip-api-c#101]
Will the geoip program eventually support the new free GeoLite2 database?

**Comment by horgh** [comment]
Did you mean `geoiplookup`?

Everything in this repository only supports the legacy database format. There are no plans to change this.

A similar command line tool for querying MMDB files is `mmdblookup` in the [libmaxminddb](https://github.com/maxmind/libmaxminddb) repository.
