### ISSUE TITLE
How can I know my location after a NAT router ?

### ISSUE THREAD

**Issue by zeusshuang** [maxmind/geoip-api-c#105]
Hi ,

Is there any way that I can lookup my location (at which country) while my IP is a  private IP (after a NAT router) but no public IP information ?

many thanks,

**Comment by oschwald** [comment]
The databases do not contain private IP addresses.

**Comment by zeusshuang** [comment]
so, if there is no public IP information on the device, there is no way to detect the device's location by geoip API ?
