### ISSUE TITLE
Why Legacy?

### ISSUE THREAD

**Issue by Neustradamus** [maxmind/geoip-api-c#108]
What is the solution to have not a legacy version?

**Comment by nchelluri** [comment]
> This library is for the GeoIP Legacy format (dat). To read the MaxMind DB format (mmdb) used by GeoIP2, please see [libmaxminddb](https://github.com/maxmind/libmaxminddb).

From https://github.com/maxmind/geoip-api-c/blob/master/README.md#important-note .

**Comment by Neustradamus** [comment]
@nchelluri: Can you add in description of this repository?
Near: "GeoIP Legacy C API"

Example:
GeoIP Legacy C API, go to https://github.com/maxmind/libmaxminddb

**Comment by nchelluri** [comment]
Hi, I think that would not be a great idea as this repo still sees significant use.
