### ISSUE TITLE
GeoIP_db_avail() doesn't distinguish between revisions

### ISSUE THREAD

**Issue by each** [maxmind/geoip-api-c#25]
GeoIP_db_avail() checks whether a file for a database exists, but doesn't check
the database type to see whether the file contains the requested edition.

I had code that tested whether GEOIP_REGION_EDITION_REV1 was available,
and if not, it would try GEOIP_REGION_EDITION_REV0. It would then open
whichever one turned out to be available. I had assumed, until I looked at the
code, that since the argument passed to GeoIP_db_avail()  was a database edition
code, that it would be checking to see whether that particular edition was 
supported or not.  However, since both editions use the same filename, 
GeoIP_db_avail() reported that REV1 was available, even when it was REV0
that was installed.  

In libGeoIP 1.5.0, a type check was added in Geoip_open_type(), so that it 
now returns NULL if the database doesn't have the expected type value.
The result is that GeoIP_open_type() can fail even if GeoIP_db_avail() just
returned true for the exact same database type, which is kind of unexpected.

I've changed my code so it no longer relies on GeoIP_db_avail(), but this still seems
like problematic behavior and I thought I'd better mention it. I can submit a patch, if it would be useful.

**Comment by oschwald** [comment]
Closing this as we included the comment and we are not likely to make significant changes to this legacy API.
