### ISSUE TITLE
The Windows documentation is out-of-date

### ISSUE THREAD

**Issue by tpoechtrager** [maxmind/geoip-api-c#48]
* Many documents state zlib is needed to build GeoIP, but that's not the case.
  GeoIP seems to build fine without zlib. Can't even find any zlib.h includes.

  To name a files few that have zlib traces:

    * Makefile.win32
    * Readme.MinGW
    * READMEwin32.txt

* READMEwin32static.txt is wrong. I don't get a static library that way.

* GeoIPWinDLL.patch seems to be out-of-date.

**Comment by oschwald** [comment]
Thanks. I think the zlib requirement is from when geoipupdate was included with libGeoIP.

**Comment by oschwald** [comment]
Do you recall what problems you had with the `nmake` directions in `READMEwin32static.txt`? I do get a static library when following them, but both it and the DLL seem to be missing the symbol for `GeoIP_region_name_by_code`  even though it is linked against the correct obj file. Otherwise it seems fine from what I can tell.

**Comment by tpoechtrager** [comment]
> Do you recall what problems you had with the nmake directions in READMEwin32static.txt?
> I do get a static library when following them

I just get a DLL and an import library, but not a static one.

Look at the link command:

    link /DLL /nologo /subsystem:console [...] /out:GeoIP.dll /implib:GeoIP.lib

> but both it and the DLL seem to be missing the symbol for GeoIP_region_name_by_code
> even though it is linked against the correct obj file. 

Wrong DLL linkage, you need to include GeoIP.h in regionName.c.

**Comment by oschwald** [comment]
Thanks. You were right on both counts.

**Comment by oschwald** [comment]
Thank you. I think all of the issues have been addressed in master now.
