### ISSUE TITLE
Licencing issues

### ISSUE THREAD

**Issue by weberhofer** [maxmind/geoip-api-c#57]
The license and copying files states the following:
"While the core libGeoIP library is licensed under the LGPL, the libGeoIPUpdate library depends on base64.c, md5.c and types.h files which are licensed under the GPL v3."

As the updated library moved to a seperate project those sections should be removed.

**Comment by oschwald** [comment]
Thanks for pointing that out. I removed that notice.

**Comment by weberhofer** [comment]
@oschwald: The COPYING file still contains a similar header.

**Comment by oschwald** [comment]
Also fixed.
