### ISSUE TITLE
Licensing issues in the release Package

### ISSUE THREAD

**Issue by weberhofer** [maxmind/geoip-api-c#58]
* The released package does not contain the LICENSE file
* The release package contains the "test-driver" which is licensed under the GPL without adding the GPL license

Sorry for bothering you with such things.

**Comment by oschwald** [comment]
Thanks for pointing these out. I fixed the missing LICENSE in dist issue, but I'll need to take a closer look at `test-driver` and how it is used.

**Comment by weberhofer** [comment]
From the SuSE reviewers I have received the following note:
"I tracked the source of test-driver file. It is the only binary file licensed under GPL. This is not an ordinary source. This is a file generated by automake, and automake itself adds it without user interaction. We apply an exception for such files: When considering license of the package, auto-generated files with GPL header are ignored.)"

**Comment by oschwald** [comment]
Yeah, it is automatically generated by the automake tools. I am not completely sure it is needed, but it sounds like it shouldn't conflict with their policy as is.

**Comment by oschwald** [comment]
Closing as the missing LICENSE file was added and the test-driver file is automatically generated by GNU tools.
