### ISSUE TITLE
RFE: integrate geoiplookup and geoiplookup6

### ISSUE THREAD

**Issue by pghmcfc** [maxmind/geoip-api-c#61]
As the world finally moves towards embracing IPv6, it would be better if looks like geoiplookup could handle IPv6 lookups themselves rather than requiring users to parse addresses themselves and choose geoiplookup6 if necessary. Other tools such as traceroute and ssh already handle IPv4 and IPv6 transparently and it would be good if geoiplookup could join them.

**Comment by oschwald** [comment]
I'd suggest using our GeoIP2 format with [mmdblookup](https://github.com/maxmind/libmaxminddb/blob/master/doc/mmdblookup.md). It is unlikely that we will make the changes to our legacy libraries and tools to support this.

**Comment by gvanem** [comment]
Someone could also make `geoiplookup*` work for Windows too. A missing `WSAStartup()` in there makes them fail on checking hostnames.

**Comment by autarch** [comment]
@gvanem - Again, we're not doing much active work on our legacy tools. If [mmdblookup](https://github.com/maxmind/libmaxminddb/blob/master/doc/mmdblookup.md) doesn't work on Windows, that is something we'd like to fix.

**Comment by oschwald** [comment]
We'd gladly accept a PR to fix this though.

**Comment by gvanem** [comment]
> We'd gladly accept a PR to fix this though.

3 lines of code! How hard can it be?

**Comment by oschwald** [comment]
Sounds like it would be a quick PR then. :-)

**Comment by gvanem** [comment]
@autarch 
> If mmdblookup doesn't work on Windows,

I have no problem with **mmdblookup** on TDM-gcc or MingW (on Windows). But it's a problem with MSVC. It doesn't have `getopt()` which *bin/mmdblookup.c* needs. How are those **project/VS12** files supposed to pull in `getopt()` (from a git-submodule)? You want a PR for that too?

**Comment by oschwald** [comment]
We should take the libmaxminddb issue there. It appears that we need a project file for mmdblookup, as we currently only have one for the library itself.

**Comment by oschwald** [comment]
Closing as future development is focused on `libmaxminddb`. We are no longer making enhancements to this library.
