### ISSUE TITLE
error handling without printf

### ISSUE THREAD

**Issue by ihrwein** [maxmind/geoip-api-c#67]
Hi,

Currently `libgeoip` prints out its error messages via `printf()` calls. It'd be nice to support more flexible error logging where the user of the library can "query" the last errors so it can also route them into its own   logs.

**Comment by oschwald** [comment]
Have you looked at the [`GEOIP_SILENCE`](https://github.com/maxmind/geoip-api-c#memory-caching-and-other-options) flag? This was introduced in 1.6.3 and stops the output to stderr. Errors should be detectable by the return values.

**Comment by oschwald** [comment]
Looking at the libGeoIP code linked to from the other issue, it appears that it does not pay attention to that flag, which should be fixed.

**Comment by ihrwein** [comment]
A return value is enough to know that there is an error but if the caller is curious about the error message it's not enough. We'd like to get the error message and forward it to the internal logs of our program. What do you think about a `GeoIP_get_last_error()` function (or something like that)?

**Comment by oschwald** [comment]
If reasonably implemented, we might accept a pull request along those lines. However, this library is mostly in maintenance mode and we are not likely to add new features ourselves. Our development efforts are focused on the MaxMind DB / GeoIP2 libraries such as [libmaxminddb](https://github.com/maxmind/libmaxminddb/) and we recommend that people upgrade to those where feasible.

**Comment by faxm0dem** [comment]
@oschwald suggests to use [libmaxminddb](/maxmind/libmaxminddb/) instead. How viable an option would that be for syslog-ng?

**Comment by ihrwein** [comment]
That would be the future proof solution but as far as I can see it also uses `fprintf` calls. 

There is a planned clean up around the submodules in syslog-ng which makes this problem harder..

I'd open a new issue in syslog-ng to switch to `libmaxminddb` and another issue for `libmaxminddb` to not use `fprintf`. We may help in the implementation. Is it okay for you?

**Comment by faxm0dem** [comment]
sorry that comment was meant to be in the syslog-ng issue

**Comment by oschwald** [comment]
@ihrwein, I am not sure which `fprintf` calls you are referring to, but if it is [these](https://github.com/maxmind/libmaxminddb/blob/9f131156bdd49881dfd105cc10301cec8f2a7f8d/src/maxminddb.c#L25), those are only enabled when compiled with `MMDB_DEBUG`. There is also `MMDB_dump_entry_data_list`, which prints to a stream provided by the caller, but it is not something most integrations would use.

**Comment by oschwald** [comment]
Given that the legacy databases have an [EOL date set](https://blog.maxmind.com/2020/06/01/retirement-of-geoip-legacy-downloadable-databases-in-may-2022/), I am going to go ahead and close this.
