### ISSUE TITLE
Wrong type return by 

### ISSUE THREAD

**Issue by pierre-laplante** [maxmind/geoip-api-c#69]
The following program is not working on a 64 bits centos 6.6 but is working on a corresponding 32 bits.
If we remove union in maxminddb.h, the program is fixed.

#include <maxminddb.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv) {
    MMDB_s mmdb;
	char *ipstr = "50.21.175.106";
	char *fname = "a.mmdb";
    int status = MMDB_open(fname, MMDB_MODE_MMAP, &mmdb);

    if (MMDB_SUCCESS != status) {
        fprintf(stderr, "\n  Can't open %s - %s\n",
                fname, MMDB_strerror(status));

        if (MMDB_IO_ERROR == status) {
            fprintf(stderr, "    IO error: %s\n", strerror(errno));
        }
        exit(1);
    }

    int gai_error, mmdb_error;
    MMDB_lookup_result_s result =
        MMDB_lookup_string(&mmdb, ipstr, &gai_error, &mmdb_error);

    if (0 != gai_error) {
        fprintf(stderr,
                "\n  Error from getaddrinfo for %s - %s\n\n",
                ipstr, gai_strerror(gai_error));
        exit(2);
    }

    if (MMDB_SUCCESS != mmdb_error) {
        fprintf(stderr,
                "\n  Got an error from libmaxminddb: %s\n\n",
                MMDB_strerror(mmdb_error));
        exit(3);
    }

    MMDB_entry_data_list_s *entry_data_list = NULL;
    MMDB_entry_data_s entry_data;
    MMDB_entry_data_list_s *ptr;
int exit_code = 0;
    if (result.found_entry) {
        int status = MMDB_get_entry_data_list(&result.entry,
                                              &entry_data_list);

        if (MMDB_SUCCESS != status) {
            fprintf(
                stderr,
                "Got an error looking up the entry data - %s\n",
                MMDB_strerror(status));
            exit_code = 4;
            goto end;
        }

        if (NULL != entry_data_list) {
            //MMDB_dump_entry_data_list(stdout, entry_data_list, 2);
        }
    } else {
        fprintf(
            stderr,
            "\n  No entry for this IP address (%s) was found\n\n",
            ipstr);
        exit_code = 5;
    }
    // Test fo find specific address

    int res = MMDB_get_value(&result.entry, &entry_data, "postal", "code", NULL);

    if (res != MMDB_SUCCESS) {
            fprintf(stderr, "%s: MMDB_get_value failure (%s).\n", ipstr, MMDB_strerror(res));
            goto end;
    }
    
    printf("Type: %d", entry_data.type);

    if (!entry_data.has_data || entry_data.type != MMDB_DATA_TYPE_UTF8_STRING) {
            fprintf(stderr, "%s: MMDB_get_value has no string data.\n", ipstr);
            goto end;
    }

	printf("size=%d\n", entry_data.data_size);

    end:
        //MMDB_free_entry_data_list(entry_data_list); // This line causes a Segfault ...
        MMDB_close(&mmdb);
        exit(exit_code);
}

size return is random and very big

**Comment by oschwald** [comment]
It appears that this report is for [libmaxminddb](https://github.com/maxmind/libmaxminddb/), not the GeoIP Legacy C API. Would you please open the issue there?
