### ISSUE TITLE
Handling extra long entries.

### ISSUE THREAD

**Issue by eternia478** [maxmind/geoip-api-c#70]
Recently I have been trying to get coordinates from a lot of IP addresses using the Geo Lite Legacy City database found [here](http://dev.maxmind.com/geoip/legacy/geolite/). While using the latest version created on November 3rd, 2015, I found that 79.22.183.0 has a weird property. If I use GEOIP_MEMORY_CACHE, then the coordinates would return (42.233299, 13.983300) for (latitude, longitude). But if I use GEOIP_STANDARD, then the coordinates would return (42.233299, -176.071106) instead.

To note, I actually found this issue due to playing around with a third-party pure Python implementation called [pygeoip](https://github.com/appliedsec/pygeoip). When this IP came up, the entire thing threw an exception because the index of reading exceeded the buffer. If I extended this buffer to read more than [FULL_RECORD_LENGTH](https://github.com/maxmind/geoip-api-c/blob/master/libGeoIP/GeoIPCity.c#L59) = 50, then I would get the longitude of 13.983300. Not reading an extra bit and instead continuing further would get me a longitude of -176.071106.

As for why I found this to create inconsistent state in the [C library](https://github.com/maxmind/geoip-api-c), I was looking into the [source code](https://github.com/maxmind/geoip-api-c/blob/master/libGeoIP/GeoIPCity.c) and found that actually, the code was more or less the same as that of pygeoip. There were two differences, both which caused this not to throw, say, a segmentation fault or whatever error with the C library (and consequentially the Maxmind official [python](https://github.com/maxmind/geoip-api-python) implementation relying on it):

1. If GEOIP_MEMORY_CACHE is set, the buffer pointer simply points to the location in memory where the entry is set. This means reading a long entry is possible even if the limit is supposed to be defined as 50. In this case, it read an extra byte "\x1d", I think.
2. If the database is not fully in memory (i.e. GEOIP_STANDARD is set), then what follows the loaded entry in the memory buffer is either zeros or garbage. Because of how C is, allocating with malloc and reading slightly past the intended length without a segfault is possible in some cases. Given the circumstances, I suspect it read an extra "\x00."

Given that the city is San Valentino In Abruzzo Citeriore, Italy, the former (reading then \x1d and getting 13.98 as a longitude) is actually correct. I suspect that because the city name was so long, it extended the entry past 50 characters and forced the longitude to be encoded in bytes 49-51. But this is somewhat weird. Isn't Maxmind's data format set so that the entry should be 50, as noted above? If anything, shouldn't the entry be limited so that, say, the city name is curtailed and the rest of the entry fits in the length of 50? Or is this some issue with the C implementation such that we should anticipate > length 50?

**Comment by oschwald** [comment]
Thanks for reporting this. I tested it out and experienced the same discrepancy that you did. We will look into the underlying cause.

**Comment by oschwald** [comment]
I believe this has been fixed. I am closing the issue, but please let us know if you see a similar issue in any future databases. As you suggested, we added additional checks to help ensure that these records were not too long. Thanks for bringing this up!
