### ISSUE TITLE
v1.5.2 GeoIP.dat Missing?

### ISSUE THREAD

**Issue by Geyup** [maxmind/geoip-api-c#73]
I need to use v1.5x with an older application that will not work with the v1.6x versions.

I tried to compiled from source v1.5.2 and received this back from the CLI:

/usr/bin/ginstall: cannot stat ‘./GeoIP.dat’: No such file or directory

I noticed upon inspection between v1.5.1 & v1.5.2 the ```Data``` directory in v1.5.2  was empty, this is all it contained; ```Makefile.am```

I would greatly appreciate it if this can be corrected?

thank you

**Comment by oschwald** [comment]
You can download [GeoIP.dat (GeoLite Legacy)](http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz) and place it in that folder.

That said, I would recommend upgrading to 1.6.7, if possible, as it has several important security and bug fixes. I believe the only breaking change involves the removal of libGeoIPUpdate.

**Comment by Geyup** [comment]
I think my problem might of been needing geoip-python.

thanks

**Comment by Geyup** [comment]
I'm trying to use this with nicotine+;

https://github.com/eLvErDe/nicotine-plus

It's an older app, but not sure it really matters, but  I can't seem to get it working with 1.6.7...

hmm
