### ISSUE TITLE
How much RAM is used when using GEOIP_MEMORY_CACHE?

### ISSUE THREAD

**Issue by simonhf** [maxmind/geoip-api-c#76]
If I hold all data in memory then how much RAM will I need?

**Comment by oschwald** [comment]
The size of the database you are using.

**Comment by simonhf** [comment]
Hmmm... so if my csv.gz file containing the GEOIP info is e.g. 700 MB, then the amount of RAM used at run-time will also be 700 MB?

**Comment by oschwald** [comment]
This API only works with the binary database files.

**Comment by simonhf** [comment]
How to convert the csv file into the binary database file format?

**Comment by oschwald** [comment]
You can download the Legacy binary database from the MaxMind website. Please direct further question to [support@maxmind.com](mailto:support@maxmind.com) or use the chat box on the MaxMind web page.

**Comment by simonhf** [comment]
Thanks. But how to convert a csv file into the legacy binary database format?
