### ISSUE TITLE
Error installing geoip-database using homebrew on macOS

### ISSUE THREAD

**Issue by sayan-sibyl** [maxmind/geoip-api-c#91]
I am trying to install geoip-database using homebrew with the following commands brew install geoip-database but brew returns this error 
brew install geoip-database
Error: No available formula with the name "geoip-database" 
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

**Comment by oschwald** [comment]
I am not familiar with a `geoip-database` formula. There is a `geoip` formula for this library. I suggest directing your question to a Homebrew support channel.
