### ISSUE TITLE
Not able to find the original GeoIP.dat file in macOS 

### ISSUE THREAD

**Issue by sayan-sibyl** [maxmind/geoip-api-c#92]
I am having this issue with GeoIP

According to the last error ettercap was not able to open the geoip file so I ran these commands
brew install geoip
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
imagemagick imagemagick@6 kubernetes-cli node-build

Warning: geoip 1.6.11 is already installed
Sayans-iMac:~ sayan$ sudo ettercap -G
Password:

ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

(process:12046): Gtk-WARNING **: Locale not supported by C library.
Using the fallback 'C' locale.

(:12046): Gtk-CRITICAL **: gtk_image_get_pixbuf: assertion 'image->storage_type == GTK_IMAGE_PIXBUF || image->storage_type == GTK_IMAGE_EMPTY' failed
Error Opening file /usr/local/var/GeoIP/GeoIP.dat
Error Opening file /path/to/GeoIP.dat

But still I get the same error and when I click on the GeoIP.dat file in finder according to this path
/usr/local/var/GeoIP/GeoIP.dat & this path
/path/to/GeoIP.dat

Finder shows me this error see the attached screenshot
https://user-images.githubusercontent.com/29756523/28931846-1d2568b8-7895-11e7-91d1-ba62a18bab69.png

**Comment by oschwald** [comment]
This seems unrelated to `libGeoIP`. I would suggest asking on an Ettercap support forum how to set up GeoIP with their software.
