### ISSUE TITLE
man page out of date

### ISSUE THREAD

**Issue by szepeviktor** [maxmind/geoip-api-c#96]
```
$ geoiplookup -h
Usage: geoiplookup [-h] [-?] [-d custom_dir] [-f custom_file] [-v] [-i] [-l] <ipaddress|hostname>
```
It seem that the man page does not cover -i and -l
Please advise.

**Comment by horgh** [comment]
Yes, the man page needs an update!

`-i` outputs information about the IP and network:

```
$ geoiplookup -i 8.8.8.8
GeoIP Country Edition: US, United States
  ipaddr: 8.8.8.8
  range_by_ip:  8.7.245.0 - 8.14.223.255
  network:      8.8.0.0 - 8.11.255.255 ::14
  ipnum: 134744072
  range_by_num: 134739200 - 135192575
  network num:  134742016 - 135004159 ::14
```

`-l` asks for output in the ISO-8859-1 character encoding. The default is UTF-8.

**Comment by oschwald** [comment]
Given that the legacy database format will be [retired in May](https://blog.maxmind.com/2020/06/retirement-of-geoip-legacy-downloadable-databases-in-may-2022), it seems unlikely that this will be fixed. I am going to go ahead and close this issue. Thank you for reporting; I apologize that it was never addressed.
